config/routes.rb
Rails.application.routes.draw do
  root "users#main"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/breweries/name", to: "breweries#by_name"
  get "/breweries/city", to: "breweries#by_city"
  get "breweries/:id/city", to: "breweries#showcity"
  get "/analytics", to: "users#analytics"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"
  post '/beers/:id/like', to: 'beers#like_beer'
  resources :breweries, only: [:index, :new, :create, :show]
  resources :beers, only: [:index, :new, :create, :show, :delete]
  resources :reviews
  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
    has_many :reviews
    has_many :beer_breweries
    has_many :users, through: :reviews
    has_many :breweries, through: :beer_breweries

    # validates :name, presence: true
    # validates :brand, presence: true
    # validates :style, presence: true
    # validates :abv, presence: true
    # validates :strength, presence: true
    # validates :likes, presence: true

    def like
        self.likes +=1
    end

    def average_rating
        if self.reviews.size > 0
        self.reviews.average(:rating) 
        else
            return 0 
        end
    end

    def self.top_beers
        Beer.all.sort_by(&:average_rating).reverse.first(10)
    end
end

app/models/beer_brewery.rb
class BeerBrewery < ApplicationRecord
    belongs_to :beer
    belongs_to :brewery
end

app/models/brewery.rb
class Brewery < ApplicationRecord
    has_many :beer_breweries
    has_many :beers, through: :beer_breweries
    validates :name, presence: true, uniqueness: true
    validates :address, presence: true, uniqueness: true
    validates :city, presence: true
    validates :zip_code, presence: true, length: { is: 5 }
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :beer
    validates :content, presence: true

    def beer_name_from_id(number)
        beer = Beer.find_by(id: number)
        beer.name
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
    has_many :beers, through: :reviews
    validates :username, presence: true
    validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
  
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  def index
    @beers = Beer.first
    @beers = Beer.all
  
  end

  def new
    @beer = Beer.new
  end

  def create
      @beer = Beer.new(beer_params)
       if @beer.valid?
        @beer.save
        redirect_to beer_path(@beer)
    else
      render :new
    end
  end

  def show
    @beer = Beer.find(params[:id])
    @beers= Beer.all
  end

  def delete
  end

  def like_beer
    @beer = Beer.find(params[:id])
    @beer.like
    @beer.save
    redirect_to action: "show"
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :brand, :style, :abv, :strength, :likes, :brewery_ids)
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

  def index
    @brewery = Brewery.new
  end

  def by_name
  end

  def by_city
  end

  def new
    @brewery = Brewery.new
  end

  def create
    @brewery = Brewery.new(brewery_params)
    if @brewery.valid?
      @brewery.save
      redirect_to @brewery
    else
      render :new
    end
  end

  def show
    @brewery = Brewery.find(params[:id])
  end

  private

  def brewery_params
    params.require(:brewery).permit(:name, :address, :city, :zip_code)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.valid?
      @review.save
      redirect_to beer_path(review_params[:beer_id])
    else
      render :new
    end
  end

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to @review
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to user_path(@review[:user_id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :tracked, :user_id, :beer_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery prepend: true, with: :exception

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else  
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:show]

  def main
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/create.html.erb
<h1>Beers#create</h1>
<p>Find me in app/views/beers/create.html.erb</p>

app/views/beers/delete.html.erb
<h1>Beers#delete</h1>
<p>Find me in app/views/beers/delete.html.erb</p>

app/views/beers/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
 <link rel="stylesheet" href="app/assets/stylesheets/beer_box.css">
    
<title>Beerdraft</title>
</head>
<body>
<br>
<%= button_to "Add a beer!", new_beer_path, method: :get %>
<br>
    <div class = "beer_header">
    </div>
        <div class="row">
        <div class="column_rev1"; >
                <div class = "beer_list3">
                <h1>Beers</h1>
                    <ul>             
                        <% @beers.each do |b| %>
                            <li>
                            <%= link_to b.name, beer_path(b) %>  <br>
                            by <%= b.brand %> <br><br>
                            </li>
                        <%end%>                   
                    </ul>       
                </div>
        </div>
        <div class="column";>
        <div class = "beer_list3">
        <h1> Top Ten Rated Beers </h1>
        <% Beer.top_beers.each do |b| %>
            <ul>
                <li>
                    <%= b.name %> rated <%= b.average_rating.round %><br>                
                </li>
            </ul>
        <% end %>
        </div>
</body>





 


  


  
  

app/views/beers/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/beer.css">
    <title>Beerdraft</title>
</head>
<body>


<div class = "beer_list4">
    Add a beer!
</div> <br>

    <div class = "beer_list2">
    
    <%= form_for @beer do |f| %>
        <%= f.label "Name:" %>
        <%= f.text_field :name %>
        <br/>
        <br/>
        <%= f.label "Brand:" %>
        <%= f.text_field :brand %>
        <br/>
        <br/>
        <%= f.label "Type:" %>
        <%= f.text_field :style %>
        <br/>
        <br/>
        <%= f.label "ABV:" %>
        <%= f.number_field :abv, in: 4.0..12.0, step: 0.5 %>
        <br/>
        <br/>
        <%= f.label "Strength:" %>
        <%= f.text_field :strength %>
        <br/>
        <br/>
        Select Brewery
        <br>
        <%= f.collection_select(:brewery_ids, Brewery.all, :id, :name)%>

        <br/>
        <br/>
        
        <%= f.submit "Add your beer!" %>
    <% end %>
    </div>

app/views/beers/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/beer.css">
    <title>Beerdraft</title>
</head>
<body>
<div class="column_rev"; >
        <div class = "beer_list4">
       <%= @beer.name %>
        </div><br>
</div>
            <div class = "beer_list3">
            Brand: <%= @beer.brand %> <br>
            Type:  <%= @beer.style %> <br>
            ABV:   <%= @beer.abv %> <br>
            Strength: <%= @beer.strength %> <br>
            <br>

            <% if @beer.average_rating == 0 %>
                    <p> Average Rating: Not rated yet</p>
                <% else %> 
                        Average Rating: <%= @beer.average_rating %> <br>
            <% end %>

            Likes: <%=@beer.likes %>  
            <%= button_to "Like", action: "like_beer" %>
            <br></br>


            <div class = "beer_list4">
                        Reviews
                        </div>
                        <div class = "beer_list1">
                        <% @beer.reviews.each do |r| %> 
                            <div class="row">
                                <div class="column_rev"; >
                                    User: <% uid = r.user_id %>
                                    <% userrecord = User.find_by id: uid %>
                                    <%= userrecord.username.capitalize %>
                                    <br>
                                    <%= link_to "Review", review_path(r[:id]) %>:  <%= r.content %> <br>
                                    Rating:  <%= r.rating %> <br>
                                    Date: <%= r.created_at %><br>
                                </div> 
                            </div>
                            <br>
                        <%end%>
                        </div>
                        <br><br>

    <%= link_to "Back to Beer lists", beers_path %> 
    

app/views/breweries/by_city.html.erb
<h1>List of cities</h1>

<% breweries = Brewery.select(:id, :city, :name).distinct%>
<ul>
<% breweries.each do |x| %>
<li><%= x.city %></li>
<% end %>
</ul>

app/views/breweries/by_name.html.erb
<h1>List of breweries by name</h1>

<% breweries = Brewery.select(:id, :name).distinct%>
<ul>
<% breweries.each do |x| %>
<li><%= link_to x.name, brewery_path(x.id) %></li>
<% end %>
</ul>

app/views/breweries/create.html.erb
<h1>Breweries#create</h1>
<p>Find me in app/views/breweries/create.html.erb</p>

app/views/breweries/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/analytics.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="brewery_index_header">
<h1>Find a brewery by name</h1>
</div>

<div class="brewery_index">
<% breweries = Brewery.select(:id, :name).distinct%>
<ul>
<% breweries.each do |x| %>
<li><%= link_to x.name, brewery_path(x.id) %></li>
<% end %>
</ul>
</div>

<%= button_to "Add New Brewery", new_brewery_path, method: :get %>
<br>
<%= button_to "Back to Beers", beers_path, method: :get %>

app/views/breweries/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/analytics.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="brewery_new_header">
<h1>Add a new brewery</h1>


<ul>
<% @brewery.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>

<div class="brewery_new">
<%= form_for @brewery do |f| %>
Name: <%= f.text_field :name %><br><br>
Address: <%= f.text_field :address %><br><br>
City: <%= f.text_field :city %><br><br>
ZIP Code: <%= f.text_field :zip_code %><br>
<%= f.submit "Add Brewery" %>
<% end %>
</div>
</body>

app/views/breweries/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/analytics.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="brewery_show_header">
<h1><%= @brewery.name %></h1>
<p><%= @brewery.address %><br>
<%= @brewery.city %>, <%= @brewery.zip_code %></p><br>
</div>

<div class="brewery_show">
Beers Sold:<% brewery = Brewery.find_by(id: @brewery) %>
<ul><% brewery.beers.each do |beer| %>
<li><%= link_to beer.name, beer_path(beer) %></li>
<% end %>
</ul>
</div>

<%= button_to "Back to Breweries", breweries_path, method: :get %>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bdraft</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/delete.html.erb
<h1>Reviews#delete</h1>
<p>Find me in app/views/reviews/delete.html.erb</p>

app/views/reviews/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/review.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="review_edit_header">
<h1> Edit a review: </h1>
</div>

<div class="review_form">
<ul>
<% @review.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>

<%= form_for @review do |f| %>
Enter review content:
<br>
<%= f.text_area :content %>
<br><br>
Select a beer<br>
<%= f.collection_select(:beer_id, Beer.all, :id, :name) %>
<br><br>
Select a user<br>
<%= f.collection_select(:user_id, User.all, :id, :username) %>
<br><br>
Enter a beer rating (1 to 5):<br>
<%= number_field(:review, :rating, in: 1.0..5.0, step: 1.0) %>
<br><br>
<%= f.check_box :tracked, {}, true, false %> Track beer
<br>
<%= f.submit %>
<% end %>
</div>
</body>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

<h2>List of reviews:</h2>
<% @reviews.each do |review| %>
Beer Name: <% @beer = Beer.find_by(id: review.beer_id) %>
<%= @beer.name %> <br>
Content: <%= review.content %><br>
Rating: <%= review.rating %><br>
Timestamp: <%= review.created_at %>
<br><br>
<% end %>

app/views/reviews/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/review.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="review_header">
<h1>Write a new review:</h1>

<ul>
<% @review.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>

<div class="new_review">
<%= form_for @review do |f| %>
Enter review content:
<br>
<%= f.text_area :content %>
<br><br>
Select a beer:<br>
<%= f.collection_select(:beer_id, Beer.all, :id, :name) %>
<br><br>
Select a user:<br>
<%= f.collection_select(:user_id, User.all, :id, :username) %>
<br><br>
Enter a beer rating (1 to 5):<br>
<%= number_field(:review, :rating, in: 1.0..5.0, step: 1.0) %>
<br><br>
<%= f.check_box :tracked, {}, true, false %> Track beer
<br><br>
<%= f.submit %>
<% end %>
</div>

</body>

app/views/reviews/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/review.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="review_show_header">
<% uid = @review.user_id %> 
<% userrecord = User.find_by id: uid %>
<%= userrecord.username.capitalize %> says:
</div>

<div class="review_main">
<br>
<%= @review.content %>
<br><br>

<% bid = @review.beer_id %>
<% beerrecord = Beer.find_by id: bid %>
<% @beername = beerrecord.name %>
<div class = "beer_list2">
<%= link_to "Back to #{@beername} info", beer_path(@review[:beer_id])%>
<br>
</div>
<%= button_to "Edit Review", edit_review_path, method: :get %>
<%= button_to "Delete Review", review_path, method: :delete %>
<%= button_to "Back to Beers Index", beers_path, method: :get %>
</div>

</body>

app/views/users/analytics.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/analytics.css">
    <title>Beerdraft</title>
</head>
<body>
<div class = "analytics-header">
<h1>Analytics</h1>
</div>
<div class = "analytics">
Total number of users: <%= @user_count = User.all.count %><br>
Total number of reviews: <%= @reviews = Review.all.count %><br>
Total number of breweries: <%= Brewery.all.count %><br>
Total number of beers: <%= Beer.all.count %><br>
<br>
Shortest review: <% reviews = Review.select(:content) %>
<% content_strings = reviews.map {|x| x.content} %>
<% @sorted_content = content_strings.sort_by {|x| x.length}%>
<%= @sorted_content[0].length %> characters<br>
Longest review: <%= @sorted_content[-1].length%> characters<br>
Latest review: "<%= @sorted_content[-1] %>"<br>
Latest review timestamp: <% reviews = Review.select(:created_at) %>
<% review_times = reviews.map{|x| x.created_at} %>
<%= review_times[-1] %>
<br><br>
Total tracked beers for all user reviews: <% reviews = Review.all %>
<% @all_reviews = reviews.map {|x| x.tracked} %>
<%= @total_tracked = @all_reviews.select{|x| x == true}.count %><br>
Tracked beers per user: <%= @total_tracked / @user_count %><br>
Average rating for all beers: <% ratings = Review.all.select(:rating) %>
<% sum = ratings.map {|x| x.rating }.sum.to_f %>
<%= sum / ratings.count %>

</div>

</body>

app/views/users/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/main.css">
    <title>Beerdraft</title>
</head>
<body>
<div class="main">
<h1>🍺 Beerdraft 🍺</h1>
<h2>A Rails application to rate and review beers</h2>
<h3>By <a href="https://github.com/jelenastj">Jelena Stjepanovic</a> and <a href="https://github.com/mattjagiello">Matt Jagiello</a></h3>
</div>
<br><br>
<p class="links">
    <%= link_to "Sign-Up", signup_path %><br><br>
    <%= link_to "Login", login_path %><br>
</p>

</body>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/signup.css">
    <title>Beerdraft</title>
</head>
<body>

<p class="info">Welcome to <b>BeerDraft</b><br><br>
Enter a <b>username</b> and <b>password</b> to create an account and begin rating beers!
</p>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>

<div class="form">
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Username" %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Password" %>
  <br>
  <%= f.submit "Create Account" %>
  </div>
<% end %>

</body>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/user_show.css">
    <title>Beerdraft</title>
</head>
<body>

<div class="user_header">
    <% if current_user == @user %>
    <div class = "beer_list4">
    <h3><%= @user.username.capitalize %>'s Beer Collection</h3>
    <% end %>
</div>
</div>

        <div class="reviewed_beers">
            
                <b>Reviewed Beers:</b>
                <% user_reviews = Review.where(user_id: @user)%>
                <% beer_ids = user_reviews.select(:beer_id).distinct %>
                    <ul>
                        <% beer_ids.each do |beer| %>
                        <% beer = Beer.find_by(id: beer.beer_id) %>
                        <li><%= link_to beer.name, beer_path(beer) %></li>
                    <% end %>
                    </ul>
           
        </div>

<div class="tracked_beers">
    <b>Tracked Beers:</b>
    <br>
    <% user_reviews = Review.where(user_id: @user) %>
        <ul>
            <% tracked_reviews = user_reviews.select {|x| x.tracked == true} %>
            <% tracked_reviews.each do |review| %>
            <% beer = Beer.find_by(id: review.beer_id) %>
        <li><%= link_to beer.name, beer_path(beer) %></li>
        <% end %>
     </ul>
</div>


    <div class="new_review">
        Write a new review:
        <%= button_to "New Review", new_review_path, method: :get %>
   
</div>
<br>
<br>
<br>

    <div class="user_links">
    Check out all the beers:
    <%= link_to "Beers", beers_path %> 
    <br>
    <br>

    Check out all the breweries:
    <%= link_to "Breweries", breweries_path %> <br><br>

</div>
<br>
<br>   
<br>
<br>

<% if logged_in? %>
    <%= button_to "Logout", root_path, method: :get %>
<% else %>
    <%= button_to "Login Page", login_path, method: :get %>
<% end %>

</body>